version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=mlflow_user
      - POSTGRES_PASSWORD=mlflow_pass
      - POSTGRES_DB=mlflow_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  mlflow:
    image: python:3.9-slim
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password123
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    depends_on:
      - postgres
      - minio
    command: bash -c "pip install mlflow psycopg2-binary boto3 && mlflow server --backend-store-uri postgresql://mlflow_user:mlflow_pass@postgres/mlflow_db --default-artifact-root s3://omr-models --host 0.0.0.0"

  omr_api:
    build: .
    container_name: omr_engine
    ports:
      - "8001:8000"
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password123
      
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - DISCORD_WEBHOOK_URL = https://discordapp.com/api/webhooks/1510835063229513749/Q9IL2feBSAqrteKmzKIOQCmp8e3BYH7ABjQW27so7uQDrNFKaGk4pKA0rqudMSGKMvyo
    depends_on:
      - minio
      - mlflow

  monitor:
    build: ./monitoring
    container_name: omr_monitor
    environment:
     - DISCORD_WEBHOOK_URL = https://discordapp.com/api/webhooks/1510835063229513749/Q9IL2feBSAqrteKmzKIOQCmp8e3BYH7ABjQW27so7uQDrNFKaGk4pKA0rqudMSGKMvyo
    depends_on:
      - omr_api
    volumes:
      - ./monitoring/demo_images:/app/demo_images

  prometheus:
    image: prom/prometheus
    container_name: omr_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: omr_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  omr_api_demo:
    build: .
    container_name: omr_api_demo
    ports:
      - "8888:8501"
    command: streamlit run app_api.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - .:/app
    depends_on:
      - omr_api
  
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    # Mount các thư mục gốc của server vào trong container (chỉ đọc) để nó quét được phần cứng
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.hwmon' # Bật bộ đếm này để lấy được thông số nhiệt độ
    ports:
      - "9100:9100"

volumes:
  pg_data:
  minio_data:
  grafana_data:
