version: "3.8"

services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped
  
  mlflow:
    image: python:3.9-slim
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres
      - minio
    command: >
      bash -c "pip install mlflow psycopg2-binary boto3 && 
      mlflow server 
      --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB} 
      --default-artifact-root s3://omr-models 
      --host 0.0.0.0"
    restart: unless-stopped

  omr_api:
    build: .
    restart: unless-stopped
    container_name: omr_engine
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - minio
      - mlflow
    volumes:
      - ./data_retrain:/app/retrain_dataset
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 2G

  monitor:
    build: ./monitoring
    container_name: omr_monitor
    depends_on:
      - omr_api
    volumes:
      - ./monitoring/demo_images:/app/demo_images
    env_file:
      - .env
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: omr_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: omr_grafana
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

  omr_api_demo:
    build: .
    container_name: omr_api_demo
    ports:
      - "8888:8501"
    command: streamlit run app_api.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - .:/app
    depends_on:
      - omr_api
    env_file:
      - .env
    restart: unless-stopped
  
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    # Mount các thư mục gốc của server vào trong container (chỉ đọc) để nó quét được phần cứng
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.hwmon' # Bật bộ đếm này để lấy được thông số nhiệt độ
    ports:
      - "9100:9100"

volumes:
  pg_data:
  minio_data:
  grafana_data:
