version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=mlflow_user
      - POSTGRES_PASSWORD=mlflow_pass
      - POSTGRES_DB=mlflow_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  mlflow:
    image: python:3.9-slim
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password123
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    depends_on:
      - postgres
      - minio
    command: bash -c "pip install mlflow psycopg2-binary boto3 && mlflow server --backend-store-uri postgresql://mlflow_user:mlflow_pass@postgres/mlflow_db --default-artifact-root s3://omr-models --host 0.0.0.0"

  omr_api:
    build: .
    container_name: omr_engine
    ports:
      - "8001:8000"
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password123
    depends_on:
      - minio
      - mlflow

  monitor:
    build: ./monitoring
    container_name: omr_monitor
    depends_on:
      - omr_api

  prometheus:
    image: prom/prometheus
    container_name: omr_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: omr_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  omr_api_demo:
    build: .
    container_name: omr_api_demo
    ports:
      - "8888:8501"
    command: streamlit run app_api.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - .:/app
    depends_on:
      - omr_api

volumes:
  pg_data:
  minio_data:
  grafana_data:
