global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'omr_monitoring'
    static_configs:
      - targets: ['monitor:8890']
  - job_name: 'server_hardware'
    static_configs:
      - targets: ['node-exporter:9100']
