global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'omr_monitoring'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['omr_api:8000']
  - job_name: 'server_hardware'
    static_configs:
      - targets: ['node-exporter:9100']
